northwesternfintech/NUTC

linter/Taskfile.yml

Add lint to taskfile

---

linter/Taskfile.yml
linter/cmake/dev-mode.cmake
linter/cmake/variables.cmake
linter/src/config.h.in
linter/src/crow/crow.cpp
linter/src/firebase/fetching.cpp
web/app/dash/layout.tsx
web/app/dash/no-submissions.tsx
web/functions/tsconfig.json

Allows for using firebase emulators with NUTC linter

Add support for local firebase endpoints

---

exchange/src/client_manager/client_manager.cpp
exchange/src/client_manager/client_manager.hpp
exchange/src/local_algos/sandbox.cpp
exchange/src/local_algos/sandbox.hpp
exchange/src/main.cpp
exchange/src/process_spawning/spawning.cpp
exchange/src/process_spawning/spawning.hpp
exchange/src/rabbitmq/client_manager/RabbitMQClientManager.cpp
exchange/src/rabbitmq/client_manager/RabbitMQClientManager.hpp
exchange/src/rabbitmq/connection_manager/RabbitMQConnectionManager.cpp
exchange/src/rabbitmq/publisher/RabbitMQPublisher.cpp

get_clients is called very often, so it doesn't make sense to construct a vector each time it's called

Removed unnecessary vector construction

---

Taskfile.yml

I think anyone who has go-task can be smart enough to make a symlink.

removing taskfile comment about go-task

---

exchange/conanfile.py
linter/conanfile.py

Resolves failing Docker/CI build

Override fmt version to fix dependency error

---

exchange/conanfile.py
linter/conanfile.py

Reverts northwesternfintech/NUTC#75

Revert "Override fmt version to fix dependency error"

---

exchange/test/src/integration/basic_algo.cpp
exchange/test/test_algos/buy_tsla_on_account.py

modified basic_algo.cpp and added buy_tsla_on_account.py to complete the integration test for the three functions.

added integration test for on_account_update function in exchange

---

web/app/dash/algoType.tsx
web/app/dash/submissions/[id]/page.tsx
web/package.json

The actual statistics shown right now are very rudimentary and I just threw them together quickly to just get some data up on the screen.

Add visualizer for data from sandboxed runs to frontend

---

exchange/src/exchange/algos/dev_mode/dev_mode.cpp
exchange/src/exchange/config.h
exchange/src/exchange/main.cpp
exchange/src/exchange/rabbitmq/consumer/RabbitMQConsumer.cpp
exchange/src/exchange/tickers/engine/engine.cpp
exchange/src/wrapper/main.cpp
exchange/src/wrapper/pywrapper/pywrapper.cpp
exchange/src/wrapper/rabbitmq/rabbitmq.cpp
exchange/template.py
web/public/template.py

Error handling especially relevant now that we have contention over rmq

Improve RMQ error handling and fix issue preventing local algos from trading

---

exchange/src/exchange/config.h
exchange/src/exchange/theo/brownian.cpp
exchange/src/exchange/theo/brownian.hpp

Copy of andrews branch but without 10k merge conflicts lol

Updated brownian motion

---

exchange/src/exchange/rabbitmq/publisher/RabbitMQPublisher.cpp
exchange/src/exchange/rabbitmq/publisher/RabbitMQPublisher.hpp
exchange/src/exchange/tickers/engine/engine.cpp
exchange/src/exchange/tickers/manager/ticker_manager.cpp
exchange/src/shared/messages_exchange_to_wrapper.hpp
exchange/src/wrapper/main.cpp
exchange/src/wrapper/rabbitmq/rabbitmq.cpp
exchange/src/wrapper/rabbitmq/rabbitmq.hpp

Fold AccountUpdate into Match message

---

exchange/src/shared/config/config.h
exchange/src/shared/config/config_loader.hpp

checks if env variable is set, if not go to config.yml
sorry for all the pings if you got them, accidentally messed up the last one a little too much

optionally set config filepath to env variable

---

exchange/CMakeLists.txt
exchange/Taskfile.yml
exchange/src/exchange/bots/bot_types/market_maker.cpp
exchange/src/exchange/bots/bot_types/market_maker.hpp
exchange/src/exchange/bots/bot_types/retail.cpp
exchange/src/exchange/bots/bot_types/retail.hpp
exchange/src/exchange/dashboard/dashboard.cpp
exchange/src/exchange/dashboard/state/ticker_state.hpp
exchange/src/exchange/traders/trader_manager.hpp
exchange/src/exchange/traders/trader_types/bot_trader.cpp
exchange/src/exchange/traders/trader_types/bot_trader.hpp
exchange/src/exchange/traders/trader_types/generic_trader.hpp

TODO: Enhance MMs tracking to include price granularity, allowing for dynamic adjustment of mid-price to theoretical value without interference from outdated orders

Improving MM + moving bid counts to quantity (vs amount)

---

docker/.gitignore
web/app/dash/page.tsx
web/app/dash/submit/page.tsx

- automatic redirecting on submit
- filtering based on search term

Polish web john

---

web/app/dash/submissions/[id]/page.tsx
web/app/registration/page.tsx

just made the submissions page a little cleaner with borders on the graphs, titles for the graphs, header, etc

prettier submissions page

---

exchange/CMakeLists.txt
exchange/src/exchange/sandbox/server/crow.cpp
exchange/src/exchange/theo/brownian.cpp

Will itemize here later. Title is generic because there's changes we need in a lot of areas

Post-NUTC SQ Changes

---

web/.gitignore

It was bothering my commits in exchange for some reason idk why but adding this may or may not be the problem, maybe it's my fault I don't know

add functions/node_modules to gitignore

---

exchange/src/exchange/tickers/matching_cycle/base/base_strategy.hpp
exchange/src/exchange/tickers/matching_cycle/dev/dev_strategy.hpp
exchange/src/exchange/traders/trader_container.hpp
exchange/src/exchange/wrappers/creation/rmq_wrapper_init.cpp
exchange/src/exchange/wrappers/creation/rmq_wrapper_init.hpp
exchange/test/src/util/helpers/test_cycle.hpp
exchange/test/src/util/process.cpp
exchange/test/src/util/process.hpp

Up to 20% faster with high trader counts

Optimize trader allocation with pmr:monotonic_buffer_resource

---

exchange/CMakeLists.txt
exchange/conanfile.py
exchange/src/exchange/orders/storage/level_quantity_tracker.cpp
exchange/src/exchange/orders/storage/level_quantity_tracker.hpp
exchange/src/exchange/orders/storage/level_update_generator.cpp
exchange/src/exchange/orders/storage/level_update_generator.hpp
exchange/src/exchange/orders/storage/orderbook.cpp
exchange/src/exchange/orders/storage/orderbook.hpp
exchange/test/CMakeLists.txt
exchange/test/src/benchmark/level_quantity_tracker.cpp
exchange/test/src/unit/matching/order_container.cpp

Extremely fast (.5ns per request if <$500, ~2ns per request if >$500)
Uses open addressing <$500 and emhash7 >$500

Extremely fast level quantity tracker for all price ranges

---

exchange/CMakeLists.txt
exchange/benchmark/CMakeLists.txt
exchange/benchmark/src/generic_trader.cpp
exchange/benchmark/src/level_quantity_tracker.cpp
exchange/conanfile.py
exchange/src/exchange/main.cpp
exchange/src/exchange/matching_cycle/base/base_strategy.cpp
exchange/src/exchange/matching_cycle/base/base_strategy.hpp
exchange/src/exchange/matching_cycle/dev/dev_strategy.hpp
exchange/src/exchange/metrics/on_tick_metrics.cpp
exchange/src/exchange/metrics/on_tick_metrics.hpp
exchange/src/exchange/orders/orderbook/cancellable_orderbook.hpp
exchange/src/exchange/orders/ticker_info.hpp
exchange/src/exchange/traders/trader_types/generic_trader.hpp
exchange/test/src/util/helpers/test_cycle.cpp
exchange/test/src/util/helpers/test_cycle.hpp

Not expecting a huge difference but may as well

Move from unordered_map to emhash

---

web/app/dash/submit/form.tsx

Add form input validation

---

.github/workflows/exchange-ci.yml

Started out a non issue, became more annoying over time

Remove darwin support
